const barriosMontevideo = [
  'Abayuba',
  'Aguada',
  'Aires Puros',
  'Arroyo Seco',
  'Atahualpa',
  'Bañados de Carrasco',
  'Barrio Sur',
  'Bella Vista',
  'Belvedere',
  'Bolívar',
  'Brazo Oriental',
  'Buceo',
  'Capurro',
  'Carrasco Norte',
  'Carrasco',
  'Casabó',
  'Casavalle',
  'Castro',
  'Centro',
  'Cerrito de la Victoria',
  'Ciudad Vieja',
  'Conciliación',
  'Cordón',
  'Flor de Maroñas',
  'Ituzaingó',
  'Jacinto Vera',
  'Jardines del Hipódromo',
  'La Blanqueada',
  'La Comercial',
  'La Figurita',
  'La Paloma',
  'La Teja',
  'Larrañaga',
  'Las Acacias',
  'Las Canteras',
  'Lavalleja',
  'Lezica',
  'Malvín Norte',
  'Malvín',
  'Manga',
  'Marconi',
  'Maroñas',
  'Melilla',
  'Mercado Modelo',
  'Noroeste',
  'Nuevo París',
  'Pajas Blancas',
  'Palermo',
  'Parque Batlle',
  'Parque Guaraní',
  'Parque Rodó',
  'Paso de la Arena',
  'Paso de las Duranas',
  'Paso Molino',
  'Peñarol',
  'Pérez Castellanos',
  'Piedras Blancas',
  'Pocitos',
  'Santiago Vázquez',
  'Toledo Chico',
  'Tomkinson',
  'Villa Dolores',
];

export default barriosMontevideo;
